version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule: { interval: "weekly" }
    labels: ["deps"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule: { interval: "weekly" }
